# Generated by Django 4.1.1 on 2022-10-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0006_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
