# Generated by Django 4.1.1 on 2022-10-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0007_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license',
            field=models.IntegerField(),
        ),
    ]
