# Generated by Django 4.1.1 on 2022-09-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0003_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprescription',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_info',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], max_length=20),
        ),
    ]
